// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcvubdQULZzwjAo5ltosuwDONMva-lVVY',
    appId: '1:813356128503:web:e587e8a478aed8f15f9bf2',
    messagingSenderId: '813356128503',
    projectId: 'phonenumberotp-323ef',
    authDomain: 'phonenumberotp-323ef.firebaseapp.com',
    storageBucket: 'phonenumberotp-323ef.appspot.com',
    measurementId: 'G-JMCHZ5CEHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6JAo-upmOPjg9D38DcnJh3_Z7fll02do',
    appId: '1:813356128503:android:99505b0be96552985f9bf2',
    messagingSenderId: '813356128503',
    projectId: 'phonenumberotp-323ef',
    storageBucket: 'phonenumberotp-323ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGELIu2vs1tzN5HhC_37LmfCazD2JLOEs',
    appId: '1:813356128503:ios:f8dad93134b3c4e65f9bf2',
    messagingSenderId: '813356128503',
    projectId: 'phonenumberotp-323ef',
    storageBucket: 'phonenumberotp-323ef.appspot.com',
    iosBundleId: 'com.example.phoneOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGELIu2vs1tzN5HhC_37LmfCazD2JLOEs',
    appId: '1:813356128503:ios:1545fa1cd10900055f9bf2',
    messagingSenderId: '813356128503',
    projectId: 'phonenumberotp-323ef',
    storageBucket: 'phonenumberotp-323ef.appspot.com',
    iosBundleId: 'com.example.phoneOtp.RunnerTests',
  );
}
